version: '3'
services:
  db:
    image: mongo
    container_name: Mongodb
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
  app:
    container_name: App
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - courses
  courses:
    container_name: Courses
    build:
      context: courses
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    links:
      - db
    environment:
      WAIT_HOSTS: db:27017
    depends_on:
      - db
      - users
  users:
    container_name: Users
    build:
      context: users
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    links:
      - db
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017
  nginx:
    container_name: Nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
      - courses
    ports:
      - 80:80
