version: '3'
services:
  app:
    volumes:
      - ./app:/www/app
    environment:
      NODE_ENV: development
    command: ["yarn", "start"]
  courses:
    volumes:
      - ./courses:/www/app
    environment:
      MONGODB_URI: mongodb://db/courses_dev
      PORT: 3000
      NODE_ENV: development
      WAIT_HOSTS: db:27017
  users:
    volumes:
      - ./users:/www/app
    environment:
      MONGODB_URI: mongodb://db/courses_dev
      PORT: 3000
      NODE_ENV: development
      WAIT_HOSTS: db:27017
